import type { TripRateSnapshot } from '@/types';

/**
 * Vero.fi (Finnish Tax Administration) 2026 tax-exempt per-diem allowances for
 * business travel — decision VH/6575/00.01.00/2025. This module is the single
 * source of truth for the euro amounts; `src/lib/per-diem-utils.ts` is the
 * pure engine that applies them to a trip's day list.
 */

export const DOMESTIC_FULL_PER_DIEM_2026 = 54;
export const DOMESTIC_PARTIAL_PER_DIEM_2026 = 25;
export const DEFAULT_FOREIGN_PER_DIEM_2026 = 52;

export const DOMESTIC_COUNTRY_CODE = 'FI';

export interface CountryRate {
  code: string;
  name: string;
  fullPerDiem: number;
}

// Foreign per-diem amounts from the Finnish Tax Administration decision on
// tax-exempt allowances for business travel in 2026 (VH/6575/00.01.00/2025, §13).
// Parsed verbatim from vero.fi; sub-region rows (e.g. "London and Edinburgh") are
// standalone entries as in the official table. Spot-checked 2026-07-11.
export const PER_DIEM_COUNTRIES_2026: CountryRate[] = [
  { code: 'afghanistan', name: "Afghanistan", fullPerDiem: 58 },
  { code: 'albania', name: "Albania", fullPerDiem: 93 },
  { code: 'algeria', name: "Algeria", fullPerDiem: 79 },
  { code: 'andorra', name: "Andorra", fullPerDiem: 66 },
  { code: 'angola', name: "Angola", fullPerDiem: 80 },
  { code: 'antiqua-and-barbuda', name: "Antiqua and Barbuda", fullPerDiem: 92 },
  { code: 'argentina', name: "Argentina", fullPerDiem: 43 },
  { code: 'armenia', name: "Armenia", fullPerDiem: 59 },
  { code: 'aruba', name: "Aruba", fullPerDiem: 66 },
  { code: 'australia', name: "Australia", fullPerDiem: 72 },
  { code: 'austria', name: "Austria", fullPerDiem: 85 },
  { code: 'azerbaidzhan', name: "Azerbaidzhan", fullPerDiem: 69 },
  { code: 'azores', name: "Azores", fullPerDiem: 72 },
  { code: 'bahamas', name: "Bahamas", fullPerDiem: 85 },
  { code: 'bahrain', name: "Bahrain", fullPerDiem: 73 },
  { code: 'bangladesh', name: "Bangladesh", fullPerDiem: 57 },
  { code: 'barbados', name: "Barbados", fullPerDiem: 75 },
  { code: 'belarus', name: "Belarus", fullPerDiem: 49 },
  { code: 'belgium', name: "Belgium", fullPerDiem: 81 },
  { code: 'belize', name: "Belize", fullPerDiem: 50 },
  { code: 'benin', name: "Benin", fullPerDiem: 48 },
  { code: 'bermuda', name: "Bermuda", fullPerDiem: 86 },
  { code: 'bhutan', name: "Bhutan", fullPerDiem: 35 },
  { code: 'bolivia', name: "Bolivia", fullPerDiem: 57 },
  { code: 'bosnia-and-hercegovina', name: "Bosnia and Hercegovina", fullPerDiem: 64 },
  { code: 'botswana', name: "Botswana", fullPerDiem: 44 },
  { code: 'brazil', name: "Brazil", fullPerDiem: 72 },
  { code: 'brunei', name: "Brunei", fullPerDiem: 43 },
  { code: 'bulgaria', name: "Bulgaria", fullPerDiem: 69 },
  { code: 'burkina-faso', name: "Burkina Faso", fullPerDiem: 32 },
  { code: 'burundi', name: "Burundi", fullPerDiem: 62 },
  { code: 'cambodia', name: "Cambodia", fullPerDiem: 65 },
  { code: 'cameroon', name: "Cameroon", fullPerDiem: 65 },
  { code: 'canada', name: "Canada", fullPerDiem: 76 },
  { code: 'canary-islands', name: "Canary Islands", fullPerDiem: 75 },
  { code: 'cape-verde', name: "Cape Verde", fullPerDiem: 46 },
  { code: 'central-african-republic', name: "Central African Republic", fullPerDiem: 104 },
  { code: 'chad', name: "Chad", fullPerDiem: 50 },
  { code: 'chile', name: "Chile", fullPerDiem: 52 },
  { code: 'china', name: "China", fullPerDiem: 69 },
  { code: 'hong-kong', name: "Hong Kong", fullPerDiem: 79 },
  { code: 'colombia', name: "Colombia", fullPerDiem: 63 },
  { code: 'comoros', name: "Comoros", fullPerDiem: 48 },
  { code: 'congo-congo-brazzaville', name: "Congo (Congo-Brazzaville)", fullPerDiem: 70 },
  { code: 'congo-democratic-republic-of-congo-kinshasa', name: "Congo, Democratic Republic of(Congo-Kinshasa)", fullPerDiem: 58 },
  { code: 'cook-islands', name: "Cook Islands", fullPerDiem: 67 },
  { code: 'costa-rica', name: "Costa Rica", fullPerDiem: 62 },
  { code: 'c-ocirc-te-d-rsquo-ivoire-ivory-coast', name: "C&ocirc;te d&rsquo;Ivoire, Ivory Coast", fullPerDiem: 86 },
  { code: 'croatia', name: "Croatia", fullPerDiem: 74 },
  { code: 'cuba', name: "Cuba", fullPerDiem: 70 },
  { code: 'cura-ccedil-ao', name: "Cura&ccedil;ao", fullPerDiem: 55 },
  { code: 'cyprus', name: "Cyprus", fullPerDiem: 65 },
  { code: 'czech-republic', name: "Czech Republic", fullPerDiem: 94 },
  { code: 'denmark', name: "Denmark", fullPerDiem: 82 },
  { code: 'djibouti', name: "Djibouti", fullPerDiem: 79 },
  { code: 'dominica', name: "Dominica", fullPerDiem: 59 },
  { code: 'dominican-republic', name: "Dominican Republic", fullPerDiem: 48 },
  { code: 'east-timor', name: "East Timor", fullPerDiem: 43 },
  { code: 'ecuador', name: "Ecuador", fullPerDiem: 59 },
  { code: 'egypt', name: "Egypt", fullPerDiem: 55 },
  { code: 'el-salvador', name: "El Salvador", fullPerDiem: 55 },
  { code: 'eritrea', name: "Eritrea", fullPerDiem: 100 },
  { code: 'estonia', name: "Estonia", fullPerDiem: 82 },
  { code: 'eswatini', name: "Eswatini", fullPerDiem: 39 },
  { code: 'ethiopia', name: "Ethiopia", fullPerDiem: 39 },
  { code: 'faroe-islands', name: "Faroe Islands", fullPerDiem: 64 },
  { code: 'fiji', name: "Fiji", fullPerDiem: 50 },
  { code: 'france', name: "France", fullPerDiem: 80 },
  { code: 'gabon', name: "Gabon", fullPerDiem: 97 },
  { code: 'gambia', name: "Gambia", fullPerDiem: 43 },
  { code: 'georgia', name: "Georgia", fullPerDiem: 46 },
  { code: 'germany', name: "Germany", fullPerDiem: 78 },
  { code: 'ghana', name: "Ghana", fullPerDiem: 49 },
  { code: 'greece', name: "Greece", fullPerDiem: 72 },
  { code: 'greenland', name: "Greenland", fullPerDiem: 65 },
  { code: 'grenada', name: "Grenada", fullPerDiem: 70 },
  { code: 'guadeloupe', name: "Guadeloupe", fullPerDiem: 55 },
  { code: 'guatemala', name: "Guatemala", fullPerDiem: 75 },
  { code: 'guinea', name: "Guinea", fullPerDiem: 83 },
  { code: 'guinea-bissau', name: "Guinea-Bissau", fullPerDiem: 46 },
  { code: 'guyana', name: "Guyana", fullPerDiem: 50 },
  { code: 'haiti', name: "Haiti", fullPerDiem: 98 },
  { code: 'honduras', name: "Honduras", fullPerDiem: 55 },
  { code: 'hungary', name: "Hungary", fullPerDiem: 72 },
  { code: 'iceland', name: "Iceland", fullPerDiem: 102 },
  { code: 'india', name: "India", fullPerDiem: 57 },
  { code: 'indonesia', name: "Indonesia", fullPerDiem: 52 },
  { code: 'iran', name: "Iran", fullPerDiem: 134 },
  { code: 'iraq', name: "Iraq", fullPerDiem: 67 },
  { code: 'ireland', name: "Ireland", fullPerDiem: 81 },
  { code: 'israel', name: "Israel", fullPerDiem: 97 },
  { code: 'italy', name: "Italy", fullPerDiem: 78 },
  { code: 'ivory-coast-c-ocirc-te-d-rsquo-ivoire', name: "Ivory Coast, C&ocirc;te d&rsquo;Ivoire", fullPerDiem: 86 },
  { code: 'jamaica', name: "Jamaica", fullPerDiem: 59 },
  { code: 'japan', name: "Japan", fullPerDiem: 64 },
  { code: 'jordania', name: "Jordania", fullPerDiem: 85 },
  { code: 'kazakhstan', name: "Kazakhstan", fullPerDiem: 57 },
  { code: 'kenya', name: "Kenya", fullPerDiem: 79 },
  { code: 'korea-democratic-people-srepublic-north-korea', name: "Korea, Democratic People'sRepublic (North Korea)", fullPerDiem: 64 },
  { code: 'korea-republic-of-south-korea', name: "Korea,Republic of (South Korea)", fullPerDiem: 78 },
  { code: 'kosovo', name: "Kosovo", fullPerDiem: 62 },
  { code: 'kuwait', name: "Kuwait", fullPerDiem: 82 },
  { code: 'kyrgystan', name: "Kyrgystan", fullPerDiem: 43 },
  { code: 'laos', name: "Laos", fullPerDiem: 35 },
  { code: 'latvia', name: "Latvia", fullPerDiem: 76 },
  { code: 'lebanon', name: "Lebanon", fullPerDiem: 103 },
  { code: 'lesotho', name: "Lesotho", fullPerDiem: 37 },
  { code: 'liberia', name: "Liberia", fullPerDiem: 61 },
  { code: 'libya', name: "Libya", fullPerDiem: 44 },
  { code: 'liechtenstein', name: "Liechtenstein", fullPerDiem: 81 },
  { code: 'lithuania', name: "Lithuania", fullPerDiem: 75 },
  { code: 'luxembourg', name: "Luxembourg", fullPerDiem: 81 },
  { code: 'madagascar', name: "Madagascar", fullPerDiem: 48 },
  { code: 'madeira', name: "Madeira", fullPerDiem: 71 },
  { code: 'malawi', name: "Malawi", fullPerDiem: 75 },
  { code: 'malaysia', name: "Malaysia", fullPerDiem: 53 },
  { code: 'maldives', name: "Maldives", fullPerDiem: 66 },
  { code: 'mali', name: "Mali", fullPerDiem: 53 },
  { code: 'malta', name: "Malta", fullPerDiem: 74 },
  { code: 'marshall-islands', name: "Marshall Islands", fullPerDiem: 67 },
  { code: 'martinique', name: "Martinique", fullPerDiem: 57 },
  { code: 'mauritania', name: "Mauritania", fullPerDiem: 46 },
  { code: 'mauritius', name: "Mauritius", fullPerDiem: 49 },
  { code: 'mexico', name: "Mexico", fullPerDiem: 74 },
  { code: 'micronesia', name: "Micronesia", fullPerDiem: 60 },
  { code: 'moldova', name: "Moldova", fullPerDiem: 81 },
  { code: 'monaco', name: "Monaco", fullPerDiem: 92 },
  { code: 'mongolia', name: "Mongolia", fullPerDiem: 31 },
  { code: 'montenegro', name: "Montenegro", fullPerDiem: 71 },
  { code: 'morocco', name: "Morocco", fullPerDiem: 75 },
  { code: 'mozambique', name: "Mozambique", fullPerDiem: 52 },
  { code: 'myanmar-formerly-burma', name: "Myanmar (formerly Burma)", fullPerDiem: 85 },
  { code: 'namibia', name: "Namibia", fullPerDiem: 38 },
  { code: 'nepal', name: "Nepal", fullPerDiem: 47 },
  { code: 'netherlands', name: "Netherlands", fullPerDiem: 88 },
  { code: 'new-zealand', name: "New Zealand", fullPerDiem: 72 },
  { code: 'nicaragua', name: "Nicaragua", fullPerDiem: 48 },
  { code: 'niger', name: "Niger", fullPerDiem: 43 },
  { code: 'nigeria', name: "Nigeria", fullPerDiem: 32 },
  { code: 'north-macedonia', name: "North Macedonia", fullPerDiem: 69 },
  { code: 'norway', name: "Norway", fullPerDiem: 72 },
  { code: 'oman', name: "Oman", fullPerDiem: 69 },
  { code: 'pakistan', name: "Pakistan", fullPerDiem: 32 },
  { code: 'palau', name: "Palau", fullPerDiem: 104 },
  { code: 'palestinian-territory', name: "Palestinian territory", fullPerDiem: 120 },
  { code: 'panama', name: "Panama", fullPerDiem: 57 },
  { code: 'papua-new-guinea', name: "Papua New Guinea", fullPerDiem: 62 },
  { code: 'paraguay', name: "Paraguay", fullPerDiem: 36 },
  { code: 'peru', name: "Peru", fullPerDiem: 51 },
  { code: 'philippines', name: "Philippines", fullPerDiem: 66 },
  { code: 'poland', name: "Poland", fullPerDiem: 84 },
  { code: 'portugal', name: "Portugal", fullPerDiem: 74 },
  { code: 'puerto-rico', name: "Puerto Rico", fullPerDiem: 69 },
  { code: 'qatar', name: "Qatar", fullPerDiem: 71 },
  { code: 'romania', name: "Romania", fullPerDiem: 74 },
  { code: 'russian-federation', name: "Russian Federation", fullPerDiem: 87 },
  { code: 'moscow', name: "Moscow", fullPerDiem: 108 },
  { code: 'st-petersburg', name: "St. Petersburg", fullPerDiem: 100 },
  { code: 'rwanda', name: "Rwanda", fullPerDiem: 31 },
  { code: 'saint-kitts-and-nevis', name: "Saint Kitts and Nevis", fullPerDiem: 62 },
  { code: 'saint-lucia', name: "Saint Lucia", fullPerDiem: 80 },
  { code: 'saint-vincent-and-the-grenadines', name: "Saint Vincent and the Grenadines", fullPerDiem: 84 },
  { code: 'samoa', name: "Samoa", fullPerDiem: 58 },
  { code: 'san-marino', name: "San Marino", fullPerDiem: 61 },
  { code: 'sao-tome-and-principe', name: "Sao Tome and Principe", fullPerDiem: 132 },
  { code: 'saudi-arabia', name: "Saudi Arabia", fullPerDiem: 75 },
  { code: 'senegal', name: "Senegal", fullPerDiem: 58 },
  { code: 'serbia', name: "Serbia", fullPerDiem: 82 },
  { code: 'seychelles', name: "Seychelles", fullPerDiem: 71 },
  { code: 'sierra-leone', name: "Sierra Leone", fullPerDiem: 58 },
  { code: 'singapore', name: "Singapore", fullPerDiem: 79 },
  { code: 'slovakia', name: "Slovakia", fullPerDiem: 85 },
  { code: 'slovenia', name: "Slovenia", fullPerDiem: 75 },
  { code: 'solomon-islands', name: "Solomon Islands", fullPerDiem: 64 },
  { code: 'somalia', name: "Somalia", fullPerDiem: 87 },
  { code: 'south-africa', name: "South Africa", fullPerDiem: 53 },
  { code: 'south-sudan', name: "South Sudan", fullPerDiem: 134 },
  { code: 'spain', name: "Spain", fullPerDiem: 78 },
  { code: 'sri-lanka', name: "Sri Lanka", fullPerDiem: 29 },
  { code: 'sudan', name: "Sudan", fullPerDiem: 134 },
  { code: 'suriname', name: "Suriname", fullPerDiem: 85 },
  { code: 'sweden', name: "Sweden", fullPerDiem: 70 },
  { code: 'switzerland', name: "Switzerland", fullPerDiem: 95 },
  { code: 'syria', name: "Syria", fullPerDiem: 86 },
  { code: 'tadzhikistan', name: "Tadzhikistan", fullPerDiem: 40 },
  { code: 'taiwan', name: "Taiwan", fullPerDiem: 69 },
  { code: 'tanzania', name: "Tanzania", fullPerDiem: 51 },
  { code: 'thailand', name: "Thailand", fullPerDiem: 63 },
  { code: 'togo', name: "Togo", fullPerDiem: 63 },
  { code: 'tonga', name: "Tonga", fullPerDiem: 62 },
  { code: 'trinidad-and-tobago', name: "Trinidad and Tobago", fullPerDiem: 78 },
  { code: 'tunisia', name: "Tunisia", fullPerDiem: 69 },
  { code: 'turkey', name: "Turkey", fullPerDiem: 43 },
  { code: 'istanbul', name: "Istanbul", fullPerDiem: 44 },
  { code: 'turkmenistan', name: "Turkmenistan", fullPerDiem: 86 },
  { code: 'uganda', name: "Uganda", fullPerDiem: 51 },
  { code: 'ukraine', name: "Ukraine", fullPerDiem: 62 },
  { code: 'united-arab-emirates', name: "United Arab Emirates", fullPerDiem: 69 },
  { code: 'united-kingdom', name: "United Kingdom", fullPerDiem: 84 },
  { code: 'london-and-edinburgh', name: "London and Edinburgh", fullPerDiem: 89 },
  { code: 'united-states', name: "United States", fullPerDiem: 86 },
  { code: 'new-york-los-angeles-washington', name: "New York, Los Angeles, Washington", fullPerDiem: 93 },
  { code: 'uruguay', name: "Uruguay", fullPerDiem: 56 },
  { code: 'uzbekistan', name: "Uzbekistan", fullPerDiem: 34 },
  { code: 'vanuatu', name: "Vanuatu", fullPerDiem: 69 },
  { code: 'venezuela', name: "Venezuela", fullPerDiem: 107 },
  { code: 'viet-nam', name: "Viet Nam", fullPerDiem: 63 },
  { code: 'virgin-islands-usa', name: "Virgin Islands (USA)", fullPerDiem: 61 },
  { code: 'yemen', name: "Yemen", fullPerDiem: 109 },
  { code: 'zimbabwe', name: "Zimbabwe", fullPerDiem: 122 },
  { code: 'zambia', name: "Zambia", fullPerDiem: 58 },
];

/** Fresh rate snapshot for a new trip — stored on the trip so later-year rate
 * changes never retroactively alter it (see `TripRateSnapshot`). */
export function buildDefaultRateSnapshot(): TripRateSnapshot {
  const countryRates: Record<string, number> = {};
  for (const c of PER_DIEM_COUNTRIES_2026) {
    countryRates[c.code] = c.fullPerDiem;
  }
  return {
    domesticFull: DOMESTIC_FULL_PER_DIEM_2026,
    domesticPartial: DOMESTIC_PARTIAL_PER_DIEM_2026,
    defaultForeign: DEFAULT_FOREIGN_PER_DIEM_2026,
    countryRates,
  };
}
